"""empty message

Revision ID: 573d8b70d7ae
Revises: 73265eb1fe07
Create Date: 2025-02-22 18:44:49.381873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573d8b70d7ae'
down_revision = '73265eb1fe07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))
        batch_op.drop_column('available')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###
